### ISSUE TITLE
@sonradanfransiz: Noticed that system tests for the fuck contain the expected output, which should not be the case. The oracle should determine the expected output, so the input is only the string.

### ISSUE THREAD

**Issue by smythi93** [smythi93/Tests4Py#79]
@sonradanfransiz: Noticed that system tests for the fuck contain the expected output, which should not be the case. The oracle should determine the expected output, so the input is only the string.

_Originally posted by @smythi93 in https://github.com/smythi93/Tests4Py/issues/13#issuecomment-2246150132_

**Comment by batuhanserce** [comment]
could you please give me an example because for example thefuck 13 (Command) takes 3 inputs such as get_new_command(Command('git branch -d hSOwZQHjXGE', '', "fatal: A branch named 'hSOwZQHjXGE' already exists."). So they are not output in most cases but inputs. Is problem the test cases or harness?

**Comment by smythi93** [comment]
You are correct. I interpreted that not correctly. The error message is part of the input.
Sorry for the confusion.

**Comment by batuhanserce** [comment]
No problem at all :)
